#
# Your Crowdin credentials
#
"project_id" : "445424"
#"api_token" : "<CROWDIN APIKEY>"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
    {
        "source": "/assets/i18n/en.json",                                       #source files filter
        "translation": "/assets/i18n/%two_letters_code%.json"        #where translations are stored
    },
    {
        "source": "/assets/searchstrings/en.json",                                       #source files filter
        "translation": "/assets/searchstrings/%two_letters_code%.json"        #where translations are stored
    },
    {
        "source": "/doc/gold/en/store_long_description.txt",                                       #source files filter
        "translation": "/doc/gold/%two_letters_code%/%original_file_name%"        #where translations are stored
    },
    {
        "source": "/doc/gold/en/store_short_description.txt",                                       #source files filter
        "translation": "/doc/gold/%two_letters_code%/%original_file_name%"        #where translations are stored
    },
    {
        "source": "/doc/normal/en/store_long_description.txt",                                       #source files filter
        "translation": "/doc/normal/%two_letters_code%/%original_file_name%"        #where translations are stored
    },
    {
        "source": "/doc/normal/en/store_short_description.txt",                                       #source files filter
        "translation": "/doc/normal/%two_letters_code%/%original_file_name%"        #where translations are stored
    }
]